### ISSUE TITLE
Debug Schema and Resolver

### ISSUE THREAD

**Issue by rimmi21-zz** [dabblelab/github-graphql-nextjs-example#1]

**Comment by Zulkarnine1** [comment]
via Hubstaff
User: Md Shahla Zulkarnine

Project: github-graphql-nextjs-example - https://app.hubstaff.com/projects/1668150
Date Range: 09/10/21 - 09/10/21
Work session total: 0:06:53
Billable: Yes

Grand total: 0:06:53

**Comment by Zulkarnine1** [comment]
via Hubstaff
User: Md Shahla Zulkarnine

Project: github-graphql-nextjs-example - https://app.hubstaff.com/projects/1668150
Date Range: 09/10/21 - 09/10/21
Work session total: 0:25:15
Billable: Yes

Grand total: 0:32:08

**Comment by Zulkarnine1** [comment]
via Hubstaff
User: Md Shahla Zulkarnine

Project: github-graphql-nextjs-example - https://app.hubstaff.com/projects/1668150
Date Range: 09/10/21 - 09/10/21
Work session total: 0:47:23
Billable: Yes

Grand total: 1:19:31
